server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HeyDdream/aispringcloud.git  #git地址
          username: HeyDdream
          password: 123456
          search-paths: config
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/